module.exports={
    development:{
        client:'mysql',
        connection:{
            host:'localhost',
            user:'root',
            password:'',
            database:'projeto_05'
        }
    }
}